### PR TITLE
Add way to display the number of points awarded for a problem

### PR DESCRIPTION
**Pull request by doersino**
I've added a way to display the number of points awarded for a problem to `homework.cls` and modified `README.md` accordingly. In order to achieve this, I had to change `\@problem[#1]` to `\@problem` in the body of the `problem` environment definition.

I'm not sure whether I've done this in the most elegant way -- this is my first attempt at advanced LaTeX.

EDIT: Showing a screenshot of how the result looks probably won't hurt (note that it's _points_ by default):
screen shot 2015-11-22 at 17 26 35

### CODE REVIEW

**Comment by artemmavrin** [comment]
Thanks for adding this feature! This is a good idea. Sorry it took me so long to merge your request, but I've been busy with school until now. Thanks again!

**Comment by artemmavrin** [comment]
I just added the `points` option for displaying points, since this merge addition interfered with how I use the `problem` environment (I sometimes write `begin{problem}[<Source of the problem>]` to include e.g. the book and chapter that the problem is taken from).

Everything should work as you intended if you use add the `points` option at the top of your files.

**Comment by artemmavrin** [comment]
Also, I didn't know about the `resume` option for the `enumerate` environment, and I can see how it can be useful. Thanks for adding that in as well!

**Comment by doersino** [comment]
> I sometimes write begin{problem}[<Source of the problem>] to include e.g. the book and chapter that the problem is taken from

Oh, I hadn't noticed that feature (it doesn't seem to be documented in `README.md`), but it would've been obvious if I'd taken a closer look at `example.tex`, my bad! Thank you for amending my changes to make the points feature work properly for everyone.

**Pull request merged**
